version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    assignees:
      - "pkalita-lbl"
    labels:
      - "python"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pkalita-lbl"
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "gh-actions"
      - "dependencies"
